name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  package-ci:
    uses: alextheman231/github-actions/.github/workflows/package-ci.yml@0776a9d83e56a216f52b56cb87ec0ff8f84a9368 # v12.3.0
    with:
      run_build: false

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@0776a9d83e56a216f52b56cb87ec0ff8f84a9368 # v12.3.0

  safe-npm-dependency-global-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Test run of safe-npm-dependency-global-install
        uses: ./actions/safe-npm-dependency-global-install
        with:
          package-name: alex-c-line
          dependency-group: devDependencies
