name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  package-ci:
    uses: alextheman231/github-actions/.github/workflows/package-ci.yml@343e1798604e0cb36cd38375eb5671b0ac33e626 # v12.7.3
    with:
      run_build: false

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@343e1798604e0cb36cd38375eb5671b0ac33e626 # v12.7.3

  safe-npm-dependency-global-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Test run of safe-npm-dependency-global-install
        uses: ./actions/safe-npm-dependency-global-install
        with:
          package-name: alex-c-line
          dependency-group: devDependencies
