name: Commit a version change
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.repository == 'alextheman231/typescript-actions' }}
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@17b0fa199995087ecc1ac109e4eda26229743802 # v10.5.0
    with:
      version-type: major
      run-build: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.repository == 'alextheman231/typescript-actions' }}
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@17b0fa199995087ecc1ac109e4eda26229743802 # v10.5.0
    with:
      version-type: minor
      run-build: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.repository == 'alextheman231/typescript-actions' }}
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@17b0fa199995087ecc1ac109e4eda26229743802 # v10.5.0
    with:
      version-type: patch
      run-build: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
